sudo: required
addons:
  chrome: stable
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
language: node_js
node_js:
  - "stable"
services:
  - "mysql"
cache:
  directories:
  - node_modules
before_script:
  - cd web
  - npm install
  - npm run start-selenium
  - npm run build-css
  - cd ../server
  - npm install
  - npm run db:dev
  - cd ../mobile
  - npm install
  - cd ..
script:
  - cd web
  - xvfb-run make test
  - npm test
  - npm run build
  - cd ../mobile
  - npm test
  - cd ../server
  - npm test
  - cd .. 

deploy:
  provider: elasticbeanstalk
  access_key_id: $EBS_ACCESS_KEY
  secret_access_key:
    secure: '$EBS_SECRET_KEY'
  region: "us-east-2"  
  app: "Cinder"
  env: "Cinder-env"
  bucket_name: "elasticbeanstalk-us-east-2-148400404701"
  skip_cleanup: true
  on:
    branch: master
