language: node_js
node_js:
  - "stable"
services:
  - "mysql"
cache:
  directories:
  - node_modules
before_script:
  - cd web
  - npm install
  - npm run start-selenium
  - npm run build-css
  - cd ../server
  - npm install
  - npm run db:dev
  - cd ../mobile
  - npm install
  - cd ..
script:
  - cd web
  - npm test
  - npm run build
  - cd ../mobile
  - npm test
  - cd ../server
  - npm test
